apiVersion: v1
kind: Service
metadata:
  name: {{ include "connect-mock.fullname" . }}
  labels:
    {{- include "connect-mock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPortA }}
      targetPort: {{ .Values.service.internalPortA }}
      protocol: TCP
      name: {{ .Values.service.nameA }}
    - port: {{ .Values.service.externalPortB }}
      targetPort: {{ .Values.service.internalPortB }}
      protocol: TCP
      name: {{ .Values.service.nameB }}
    - port: {{ .Values.service.externalPortC }}
      targetPort: {{ .Values.service.internalPortC }}
      protocol: TCP
      name: {{ .Values.service.nameC }}
  selector:
    {{- include "connect-mock.selectorLabels" . | nindent 4 }}
